# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfefb3078ebbc36f4274d4d074d2c2d830c9a3e5805ee91471e820aca5a4eea0e3cfb6621b95a775437773763ea72f2e09e0443c849e2f10846b109be432635

test:
  secret_key_base: 7409ebf99a53f549fa2c9efb0380ba67a9c157a07ee91fe2dc3ce97bc113a153b2bc67c1d8d8bb41f788c70d038bf4217d395b3b3b048431dea2cf71cff32155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
